### ISSUE TITLE
Merge changes and improvements from Cisco

### ISSUE THREAD

**Issue by slifty** [prior-art-archive/query-parser#1]
Over the past few months there have been improvements to the query parser which we need to ultimately merge into this project.  In future we should make sure that work done is more granular and linked to github issues, but since we didn't have that development process in place before we'll do a larger combining just to get everybody working from the same baseline.

**Comment by reefdog** [comment]
Cisco's latest has been brought in as a [whole new repo](https://github.com/prior-art-archive/query-parser-docker/).
